import os
import subprocess
import csv
import io
import sys

import matplotlib.pyplot as plt


# --- Config chemins --- #
REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
SIM_PC_DIR = os.path.join(REPO_ROOT, ".")
BUILD_DIR = os.path.join(SIM_PC_DIR, "build")
BIN_DIR = os.path.join(BUILD_DIR, "bin")

if os.name == "nt":
    EXE_NAME = "fc_sim_pc.exe"
else:
    EXE_NAME = "fc_sim_pc"

EXE_PATH = os.path.join(BIN_DIR, EXE_NAME)

# stdout backup
STDOUT_CSV_PATH = os.path.join(REPO_ROOT, "last_run.csv")

# new file produced by your embedded-style sim
EMBEDDED_CSV_PATH = os.path.join(SIM_PC_DIR, "telemetry.csv")
EMBEDDED_BIN_PATH = os.path.join(SIM_PC_DIR, "telemetry.bin")


def run(cmd, cwd=None):
    print(f"\n$ {' '.join(cmd)}")
    subprocess.run(cmd, cwd=cwd, check=True)


def read_csv_text_prefer_file(stdout_text: str) -> str:
    """
    Prefer the CSV file generated by the sim (telemetry.csv).
    Fallback to stdout if the file is missing/empty.
    """
    if os.path.exists(EMBEDDED_CSV_PATH):
        try:
            with open(EMBEDDED_CSV_PATH, "r", encoding="utf-8") as f:
                txt = f.read().strip()
                if txt:
                    return txt
        except OSError:
            pass

    return stdout_text.strip()


def col(row, name, default=0.0):
    v = row.get(name, "")
    if v == "" or v is None:
        return default
    return float(v)


def main():
    # 1) Configure + build C (sim_pc)
    os.makedirs(BUILD_DIR, exist_ok=True)
    run(["cmake", "-S", ".", "-B", "build"], cwd=SIM_PC_DIR)
    run(["cmake", "--build", "build"], cwd=SIM_PC_DIR)

    # 2) Run exe, capture stdout
    print(f"\nRunning {EXE_PATH} ...")
    proc = subprocess.run(
        [EXE_PATH],
        cwd=SIM_PC_DIR,
        capture_output=True,
        text=True,
        check=True,
    )

    stdout = proc.stdout

    # Save stdout backup
    with open(STDOUT_CSV_PATH, "w", newline="", encoding="utf-8") as f:
        f.write(stdout)
    print(f"\nStdout backup saved to: {STDOUT_CSV_PATH}")

    # Inform about embedded outputs
    if os.path.exists(EMBEDDED_CSV_PATH):
        print(f"Embedded CSV detected: {EMBEDDED_CSV_PATH}")
    if os.path.exists(EMBEDDED_BIN_PATH):
        print(f"Embedded BIN detected: {EMBEDDED_BIN_PATH}")

    # 3) Prefer parsing telemetry.csv (written by embedded code)
    csv_text = read_csv_text_prefer_file(stdout)

    # 4) Parse CSV
    reader = csv.DictReader(io.StringIO(csv_text), skipinitialspace=True)

    time = []
    motor1 = []
    motor2 = []
    motor3 = []
    motor4 = []

    sim_az = []
    sim_vz = []
    sim_pz = []
    setpoint = []

    dt = []
    e_vz = []
    u_p = []
    u_i = []
    u_d = []
    u_raw = []
    u_sat = []
    vz_est = []
    pz_est = []

    # Optional column if you re-add it later
    az_state = []
    has_az_state = False

    for row in reader:
        # mandatory-ish columns
        time.append(col(row, "time"))
        motor1.append(col(row, "motor1"))
        motor2.append(col(row, "motor2"))
        motor3.append(col(row, "motor3"))
        motor4.append(col(row, "motor4"))

        sim_az.append(col(row, "sim_az"))
        sim_vz.append(col(row, "sim_vz"))
        sim_pz.append(col(row, "sim_pz"))
        setpoint.append(col(row, "setpoint"))

        dt.append(col(row, "dt"))
        e_vz.append(col(row, "e_vz"))
        u_p.append(col(row, "u_p"))
        u_i.append(col(row, "u_i"))
        u_d.append(col(row, "u_d"))
        u_raw.append(col(row, "u_raw"))
        u_sat.append(col(row, "u_sat"))
        vz_est.append(col(row, "vz_est"))
        pz_est.append(col(row, "pz_est"))

        # optional
        if "az_state" in row:
            has_az_state = True
            az_state.append(col(row, "az_state"))
        else:
            az_state.append(0.0)

    if not time:
        print("\nNo data parsed. Check that your sim prints CSV to stdout or writes telemetry.csv.")
        return

    # 5) Plot
    # if az_state exists, add one extra subplot
    n_axes = 7 if has_az_state else 6
    fig, axes = plt.subplots(n_axes, 1, sharex=True, figsize=(10, 11 if has_az_state else 10))

    # Position/altitude
    axes[0].plot(time, sim_pz, label="pz (sim)")
    axes[0].plot(time, pz_est, "--", label="pz_est (FC)")
    axes[0].set_ylabel("z [m]")
    axes[0].legend()
    axes[0].grid(True)

    # Vertical speed
    axes[1].plot(time, sim_vz, label="vz (sim)")
    axes[1].plot(time, vz_est, "--", label="vz_est (FC)")
    axes[1].plot(time, setpoint, ":", label="vz_set")
    axes[1].set_ylabel("vz [m/s]")
    axes[1].legend()
    axes[1].grid(True)

    # Optional acceleration state plot
    offset = 0
    if has_az_state:
        axes[2].plot(time, az_state, label="az_state (SI)")
        axes[2].set_ylabel("az_state")
        axes[2].legend()
        axes[2].grid(True)
        offset = 1

    # Error
    axes[2 + offset].plot(time, e_vz)
    axes[2 + offset].set_ylabel("e_vz")
    axes[2 + offset].grid(True)

    # PID terms
    axes[3 + offset].plot(time, u_p, label="P")
    axes[3 + offset].plot(time, u_i, label="I")
    axes[3 + offset].plot(time, u_d, label="D")
    axes[3 + offset].set_ylabel("PID terms")
    axes[3 + offset].legend()
    axes[3 + offset].grid(True)

    # Control output
    axes[4 + offset].plot(time, u_raw, label="u_raw")
    axes[4 + offset].plot(time, u_sat, label="u_sat")
    axes[4 + offset].set_ylabel("u")
    axes[4 + offset].legend()
    axes[4 + offset].grid(True)

    # dt
    axes[5 + offset].plot(time, dt)
    axes[5 + offset].set_ylabel("dt [s]")
    axes[5 + offset].set_xlabel("time [s]")
    axes[5 + offset].grid(True)

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as e:
        print("\nERROR while running command:", e.cmd, file=sys.stderr)
        print("Return code:", e.returncode, file=sys.stderr)
        sys.exit(e.returncode)
